server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/newspace-msa/newspace-config.git
          default-label: main
          search-paths:
            - eureka
            - gateway
            - user
            - news
            - notice
        bootstrap: true

  rabbitmq:
    host: 44.212.8.226
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics