server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/newspace-msa/newspace-config.git
          default-label: main
          search-paths:
            - eureka
            - gateway
            - user
            - news
            - notice
        bootstrap: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: newspace-config-service
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://newspace-eureka:8070/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics